sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t loveisall/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true loveisall/react-test npm test

after_success:
  - docker build -t loveisall/multi-client-10-14 ./client
  - docker build -t loveisall/multi-nginx-10-14 ./nginx
  - docker build -t loveisall/multi-server-10-14 ./server
  - docker build -t loveisall/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push loveisall/multi-client-10-14
  - docker push loveisall/multi-nginx-10-14
  - docker push loveisall/multi-server-10-14
  - docker push loveisall/multi-worker-10-14

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-998626419377'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
